#Despliegue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despacho
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-despacho 
  template:
    metadata:
      labels:
        app: backend-despacho
    spec:
      containers:
        - name: backend
          image: 637423579746.dkr.ecr.us-east-1.amazonaws.com/despacho-project-backend-despachos:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/despacho
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
#Service:
apiVersion: v1
kind: Service
metadata:
  name: backend-despacho
spec:
  selector:
    app: backend-despacho 
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP